arch: "clip"
#resume: 'networks/UniversalFakeDetect/fc_weights.pth'
#resume: 'logs/Ojha—ProganPart1_20240315_08_28_33/epoch=78-val_acc_epoch=0.79.ckpt' # part1
#resume: 'logs/Ojha—ProganPart2_20240315_19_16_55/epoch=32-val_acc_epoch=0.82.ckpt' # part2
#resume: 'logs/Ojha—ProganPart3_20240315_19_17_00/epoch=12-val_acc_epoch=0.81.ckpt' # part3
#resume: 'logs/Ojha—Progan_less_20240324_19_24_35/epoch=12-val_acc_epoch=0.69-v1.ckpt' # less
resume: 'logs/Ojha—SD15_20240327_13_56_09/last.ckpt' # 使用sd1.5作为base训练集
test_name: "Ojha_SD15_224"

dataset:
  train:
    mode: 'binary'
    dataroot: "/home/jwang/ybwork/data/deepfake_benchmark/"
    subfolder_names: ["ForenSynths"]
    multicalss_idx: [1]
    batch_size: 256
    loader_workers: 32
    loadSize: 256
    cropSize: 224
    random_flip: true
    augment: null


datasets:
  batch_size: 32
  loader_workers: 8

  trsf:
    - _target_: torchvision.transforms.Resize
      size: 256
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

  source:
    DiffusionForensics:
      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/DiffusionForensics"
      sub_sets: ['imagenet_sdv1', 'imagenet_adm', 'lsun_bedroom_sdv1_new1', 'lsun_bedroom_sdv1_new2',
                 'lsun_bedroom_adm', 'lsun_bedroom_iddpm', 'lsun_bedroom_ddpm', 'lsun_bedroom_pndm',
                 'lsun_bedroom_sdv2', 'lsun_bedroom_ldm', 'lsun_bedroom_vqdiffusion', 'lsun_bedroom_if',
                 'lsun_bedroom_dalle2', 'lsun_bedroom_midjourney', 'celebahq_sdv2', 'celebahq_if',
                 'celebahq_dalle2', 'celebahq_midjourney']

    AIGCDetect:
      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/AIGCDetect"
      sub_sets: ['stylegan', 'stylegan2', 'wukong', 'DALLE2', 'cyclegan', 'Midjourney',
                 'stable_diffusion_v_1_5', 'stargan', 'whichfaceisreal', 'ADM', 'biggan', 'Glide', 'gaugan',
                 'progan', 'stable_diffusion_v_1_4', 'VQDM']

    ForenSynths:
      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/ForenSynths/"
      sub_sets: ["biggan", "crn", "cyclegan", "deepfake", "gaugan", "imle", "progan", "san", "seeingdark", "stargan",
                   "stylegan", "stylegan2", "whichfaceisreal"]

    Ojha:
      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/Ojha"
      sub_sets: ["dalle", "glide_100_10", "glide_100_27", "glide_50_27", "guided", "ldm_100", "ldm_200", "ldm_200_cfg"]

    AntifakePrompt:
      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/AntifakePrompt"
      sub_sets: ['COCO', 'Flickr', 'AdvAtk', 'DALLE2', 'Deeperforensics', 'IF', 'lte', 'SD2Inpaint', 'SDXL',
                 'Backdoor', 'Control', 'DataPoison', 'Lama', 'SD2', 'SD2SuperRes', 'SGXL']

#    Celeb-DF-v1:
#      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/Celeb-DF-v1"
#      sub_sets: ['all']
#
#    Celeb-DF-v2:
#      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/Celeb-DF-v2"
#      sub_sets: ['all']
#
#    UADFV:
#      data_root: "/home/jwang/ybwork/data/deepfake_benchmark/UADFV"
#      sub_sets: ['all']
