arch: "arp"
resume: null
name: "arpaug-ViTL-a1b1c1-811-ProGAN"

train:
  gpu_ids: [0]
  train_epochs: 2
  gradient_accumulation_steps: 1
  check_val_every_n_epoch: 1

  a: 1
  b: 1
  c: 1

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: 1e-4
    weight_decay: 1e-3

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: 2

model:
  NAME: "ViT-L/14"
  N_CTX_VISION: 16
  N_CTX_TEXT: 16
  CTX_INIT: False
  PROMPT_DEPTH_VISION: 8
  PROMPT_DEPTH_TEXT: 1
  PROMPT_NUM_TEXT: 1


dataset:
  train:
    dataroot: "/scratch/yw26g23/datasets/deepfakebenchmark/"
#    dataroot: "/home/jwang/ybwork/data/DFBenchmark/"
    subfolder_names: "ForenSynths" #"GenImg_MJ" "GenImg_SD15"
    multicalss_names: ["airplane", "bird", "bottle", "car", "chair", "diningtable", "horse", "person", "sheep", "train",
                       "bicycle", "boat", "bus", "cat", "cow", "dog", "motorbike", "pottedplant", "sofa", "tvmonitor"]
    batch_size: 128
    loader_workers: 32
    loadSize: 256
    cropSize: 224
    random_flip: true
    augment: True
    blur_prob: 0.1
    blur_sig: [0.0, 1.0]
    jpg_method: ['cv2', 'pil']
    jpg_prob: 0.1
    jpg_qual: [60, 100]

  val:
    dataroot: "/scratch/yw26g23/datasets/deepfakebenchmark/ForenSynths/test"
#    dataroot: "/home/jwang/ybwork/data/DFBenchmark/ForenSynths/test"
    subfolder_names: ["progan"]
    multicalss_idx: [1]
#    subfolder_names: [ "biggan", "deepfake", "whichfaceisreal", "gaugan" ]
#    multicalss_idx: [ 0, 0, 0, 0 ]
    batch_size: 32
    loader_workers: 4
    loadSize: 256
    cropSize: 224


