arch: "vlp"  # Architecture for binary classification, e.g., 'resnet50.tv_in1k' 'vit_base_patch16_224'
resume: null
name: "vlp-SPrompts-ViTL-ProGAN"


train:
  gpu_ids: [0]  # GPU IDs to use for training, e.g., '0' for single GPU or '0,1,2,3' for multiple GPUs
  train_epochs: 20  # Number of training epochs
  gradient_accumulation_steps: 1
  check_val_every_n_epoch: 1

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: 1e-4
    weight_decay: 1e-3

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: 20

model:
  NAME: "ViT-L/14"
  N_CTX_VISION: 16
  N_CTX_TEXT: 16
  CTX_INIT: False
  PROMPT_DEPTH_VISION: 1
  PROMPT_DEPTH_TEXT: 1
  PROMPT_NUM_TEXT: 2


dataset:
  train:
    mode: 'binary'
    dataroot: "/scratch/yw26g23/datasets/deepfakebenchmark/"
#    dataroot: "/home/jwang/ybwork/data/deepfake_benchmark/"
    subfolder_names: ["ForenSynths"]
    multicalss_idx: [1]
#    subfolder_names: ["GenImg_SD15"]
#    subfolder_names: [ "GenImg_MJ" ]
#    multicalss_idx: [0]
    batch_size: 256
    loader_workers: 32
    loadSize: 256
    cropSize: 224
    random_flip: true
    augment: null

  val:
    mode: 'binary'
    dataroot: "/scratch/yw26g23/datasets/deepfakebenchmark/ForenSynths/test"
#    dataroot: "/home/jwang/ybwork/data/deepfake_benchmark/ForenSynths/test"
    subfolder_names: ["biggan", "deepfake", "whichfaceisreal", "gaugan"]
    multicalss_idx: [0, 0, 0, 0]
    batch_size: 256
    loader_workers: 4
    loadSize: 256
    cropSize: 224


